export { matrimonio } from './scripts/matrimonio.js'
export { nomatrimonio } from './scripts/nomatrimonio.js'
export { carpeta } from './scripts/carpeta.js'
export { cotizaciones } from './scripts/cotizaciones.js'
export { declaracion } from './scripts/declaracion.js'
export { deuda } from './scripts/deuda.js'
export { formulario22 } from './scripts/formulario22.js'
export { test } from './scripts/test.js'
